### ISSUE TITLE
getting memory utilization

### ISSUE THREAD

**Issue by ReinsBrain** [JerrySievert/node-judy#11]
I'm intrigued with judy array - my use is long-lived arrays so instance cost (in time) doesn't scare me off. i do worry about memory utilization - given enough time i could overflow available memory - it would be nice to know how much memory space a given array is occupying so i could "clean it up" every-so-often.

Would it be feasible and desirable to have a method on a judy array to emit memory usage? And, could I contribute it? 

I think it would look something similar to this:
https://github.com/JerrySievert/node-judy/blob/master/src/judy64nb.c#L386

**Comment by JerrySievert** [comment]
I have an alternate implementation - let me benchmark both, and see which is fastest.

**Comment by JerrySievert** [comment]
see https://github.com/JerrySievert/judy-revisited - I've updated it quite a bit, and added `size()` which will return both the key count, and the amount of memory allocated for both keys and values.

note, that call is kind of expensive, as it iterates through the whole JudyArray.

**Comment by JerrySievert** [comment]
@rebelstackio - please check out the project I posted, I think you'll find it a bit better :)

**Comment by JerrySievert** [comment]
fyi, using `sizeof` isn't what you probably want to do:

```
> arr.set('foo', 'bar');
true
> arr.size();
{ keyCount: 1, memoryAllocated: 8, sizeof: 8 }
> arr.set('hello', 'world');
true
> arr.size();
{ keyCount: 2, memoryAllocated: 20, sizeof: 8 }
```

**Comment by ReinsBrain** [comment]
Thanks Jerry, I didn't know about https://github.com/JerrySievert/judy-revisited which makes my additions irrelevant if not ill-advised :)

**Comment by JerrySievert** [comment]
no reason you should have known about it, as I just released it yesterday :)
