### ISSUE TITLE
Implementation of Judy Arrays in C

### ISSUE THREAD

**Issue by saru95** [JerrySievert/node-judy#9]
Hi ! I came across your blog post on Judy Arrays. I'm looking to implement Judy Arrays in C (not C++). Can you please brief me about how you have implemented it ? 
Newbie here.

Thanks.

**Comment by JerrySievert** [comment]
https://github.com/jerrysievert/judyarray

this is a fork of the original source that lived on code.google.com (see the README for API usage), I did not do the implementation.

I would recommend looking at https://github.com/JerrySievert/judyarray/blob/master/judy64nb.c - this will give you integer and string support, and will work fairly well.  link against this.

an example implementation (in c) can be found at: https://github.com/JerrySievert/node-judy/blob/master/src/judy.cc#L21-L90

this is the `jg_init`, `jg_get`, `jg_set`, and `jg_delete1 methods.  you might need to make a couple of small changes to make sure it works in `c` directly, but it should be straightforward.  you'll also need to create your own `judy.h`, or adapt it from https://github.com/JerrySievert/node-judy/blob/master/src/judy64nb.h

hope that helps!
